# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: treeserve.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftreeserve.proto\x12\x10\x61pi.treeserve.v1\"#\n\rDeployRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"$\n\x0e\x44\x65ployResponse\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"!\n\x0bInfoRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"\x1c\n\x0cInfoResponse\x12\x0c\n\x04info\x18\x01 \x03(\t\"I\n\x0ePredictRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x12\n\ninput_data\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x05\":\n\x0fPredictResponse\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x13\n\x0bpredictions\x18\x03 \x03(\x01\x32\xf7\x01\n\x11\x44\x65ploymentService\x12K\n\x06\x44\x65ploy\x12\x1f.api.treeserve.v1.DeployRequest\x1a .api.treeserve.v1.DeployResponse\x12\x45\n\x04Info\x12\x1d.api.treeserve.v1.InfoRequest\x1a\x1e.api.treeserve.v1.InfoResponse\x12N\n\x07Predict\x12 .api.treeserve.v1.PredictRequest\x1a!.api.treeserve.v1.PredictResponseB\x1dZ\x1b/pkg/pb/treeserve;treeserveb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'treeserve_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\033/pkg/pb/treeserve;treeserve'
  _DEPLOYREQUEST._serialized_start=37
  _DEPLOYREQUEST._serialized_end=72
  _DEPLOYRESPONSE._serialized_start=74
  _DEPLOYRESPONSE._serialized_end=110
  _INFOREQUEST._serialized_start=112
  _INFOREQUEST._serialized_end=145
  _INFORESPONSE._serialized_start=147
  _INFORESPONSE._serialized_end=175
  _PREDICTREQUEST._serialized_start=177
  _PREDICTREQUEST._serialized_end=250
  _PREDICTRESPONSE._serialized_start=252
  _PREDICTRESPONSE._serialized_end=310
  _DEPLOYMENTSERVICE._serialized_start=313
  _DEPLOYMENTSERVICE._serialized_end=560
# @@protoc_insertion_point(module_scope)
