# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mldeploy.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emldeploy.proto\x12\x0f\x61pi.mldeploy.v1\"#\n\rDeployRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"$\n\x0e\x44\x65ployResponse\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"!\n\x0bInfoRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"\x1c\n\x0cInfoResponse\x12\x0c\n\x04info\x18\x01 \x03(\t\"I\n\x0ePredictRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x12\n\ninput_data\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x05\":\n\x0fPredictResponse\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x13\n\x0bpredictions\x18\x03 \x03(\x01\x32\xf1\x01\n\x11\x44\x65ploymentService\x12I\n\x06\x44\x65ploy\x12\x1e.api.mldeploy.v1.DeployRequest\x1a\x1f.api.mldeploy.v1.DeployResponse\x12\x43\n\x04Info\x12\x1c.api.mldeploy.v1.InfoRequest\x1a\x1d.api.mldeploy.v1.InfoResponse\x12L\n\x07Predict\x12\x1f.api.mldeploy.v1.PredictRequest\x1a .api.mldeploy.v1.PredictResponseB\x1bZ\x19/pkg/pb/mldeploy;mldeployb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mldeploy_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\031/pkg/pb/mldeploy;mldeploy'
  _DEPLOYREQUEST._serialized_start=35
  _DEPLOYREQUEST._serialized_end=70
  _DEPLOYRESPONSE._serialized_start=72
  _DEPLOYRESPONSE._serialized_end=108
  _INFOREQUEST._serialized_start=110
  _INFOREQUEST._serialized_end=143
  _INFORESPONSE._serialized_start=145
  _INFORESPONSE._serialized_end=173
  _PREDICTREQUEST._serialized_start=175
  _PREDICTREQUEST._serialized_end=248
  _PREDICTRESPONSE._serialized_start=250
  _PREDICTRESPONSE._serialized_end=308
  _DEPLOYMENTSERVICE._serialized_start=311
  _DEPLOYMENTSERVICE._serialized_end=552
# @@protoc_insertion_point(module_scope)
